In [18]:
import tensorflow as tf
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.models import Sequential
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

# Set the input shape and number of classes
INPUT_SHAPE = (128, 128, 3)  # Assume 128x128 RGB images
NUM_CLASSES = 2  # Food or not food

# Set the batch size
BATCH_SIZE = 64

# Set the directory containing the images
image_dir = 'food_images_2'

# Create an ImageDataGenerator object with the preprocessing function
image_generator = ImageDataGenerator(rescale=1./255, validation_split=0.2)

# Use the generator to load the images from the directory
train_data_gen = image_generator.flow_from_directory(image_dir,
                                                     target_size=(128, 128),
                                                     color_mode='rgb',
                                                     class_mode='binary',
                                                     batch_size=32,
                                                     subset='training')
val_data_gen = image_generator.flow_from_directory(image_dir,
                                                   target_size=(128, 128),
                                                   color_mode='rgb',
                                                   class_mode='binary',
                                                   batch_size=32,
                                                   subset='validation')

# Get the images and labels from the generator
x_train, y_train = next(train_data_gen)
x_val, y_val = next(val_data_gen)

# Define the model
model = Sequential()

# Add convolutional layers
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=INPUT_SHAPE))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(256, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

# Flatten the output and add a fully connected layer for classification
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(NUM_CLASSES, activation='softmax')) 

# print model output shape
print(model.output_shape)

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Found 800 images belonging to 1 classes.
Found 199 images belonging to 1 classes.
(None, 2)


In [21]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(y_val.shape)

print(x_train[0])

# Train the model
history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=10)



(32, 128, 128, 3)
(32,)
(32, 128, 128, 3)
(32,)
[[[0.18431373 0.227451   0.2509804 ]
  [0.12941177 0.16470589 0.18431373]
  [0.1137255  0.14901961 0.16862746]
  ...
  [0.92549026 0.8980393  0.8588236 ]
  [0.91372555 0.8980393  0.8862746 ]
  [0.8352942  0.8352942  0.8352942 ]]

 [[0.15294118 0.19607845 0.21960786]
  [0.11764707 0.15294118 0.17254902]
  [0.10980393 0.14509805 0.16470589]
  ...
  [0.7294118  0.7058824  0.65882355]
  [0.854902   0.8431373  0.81568635]
  [0.8235295  0.8196079  0.8000001 ]]

 [[0.16470589 0.20784315 0.23137257]
  [0.12156864 0.15686275 0.1764706 ]
  [0.09803922 0.13333334 0.15294118]
  ...
  [0.5411765  0.50980395 0.4666667 ]
  [0.6039216  0.5882353  0.54509807]
  [0.6666667  0.65882355 0.6117647 ]]

 ...

 [[0.8470589  0.81568635 0.80392164]
  [0.8470589  0.8078432  0.8000001 ]
  [0.8313726  0.7960785  0.7686275 ]
  ...
  [0.5647059  0.6862745  0.8078432 ]
  [0.5686275  0.6901961  0.8117648 ]
  [0.5764706  0.69803923 0.8196079 ]]

 [[0.86666673 0.8352942  0

ValueError: in user code:

    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/engine/training.py", line 1024, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/engine/training.py", line 1082, in compute_loss
        return self.compiled_loss(
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/losses.py", line 284, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/losses.py", line 2176, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/backend.py", line 5680, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(

    ValueError: `logits` and `labels` must have the same shape, received ((32, 2) vs (32, 1)).


In [5]:
import numpy as np


# Evaluate the model on the test data
loss, accuracy = model.evaluate(x_test, y_test)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

# Make predictions on the test data
predictions = model.predict(x_test)

# Convert the predictions to a one-hot encoded form
predictions = np.argmax(predictions, axis=1)

# Convert the true labels to a one-hot encoded form
y_test = np.argmax(y_test, axis=1)

# Create the confusion matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

NameError: name 'x_test' is not defined